const base = import.meta.env.VITE_API_BASE_URL || '/api'
export type Session={token:string;user:{id:string;displayName:string;role:string}}
export type Paper={id:string;title:string;subject:string;grade:string;pageCount:number;questionCount:number;reviewedCount:number;progress:number;status:string;errorCode?:string;errorMessage?:string;createdAt:string}
export type PresentationBlock={id:string;kind:'stem'|'options'|'figure';figureIndex?:number;x:number;y:number;width:number;height?:number}
export type PresentationLayout={width?:number;height?:number;blocks?:PresentationBlock[];figurePosition?:'above'|'below'|'inline'}
export type Question={id:string;paperId:string;number:number;type:string;stem:string;options:string[];answer:string;analysis:string;points:number;confidence:number;difficulty:string;status:string;version:number;sourceTitle?:string;sourceSubject?:string;sourceGrade?:string;knowledgePointIds?:string[];sourceRegions?:Array<{pageNumber:number;x0:number;y0:number;x1:number;y1:number}>;boundaryQuality?:{score:number;blockCount:number;crossPage:boolean;requiresManualReview:boolean};warnings?:string[];cropUrls?:string[];figureUrls?:string[];presentationLayout?:PresentationLayout}
export type KnowledgePoint={id:string;parentId?:string|null;subject:string;grade:string;name:string;sortOrder:number;questionCount:number}
export type ProcessingDetail={jobId:string;status:string;stage:string;progress:number;errorCode?:string;errorMessage?:string;stages:Array<{stage:string;status:string;attempt:number;provider:string;errorCode?:string;errorMessage?:string}>;pages:Array<{pageNumber:number;sourceType:string;strategy:string;hasTextLayer:boolean;nativeTextScore:number;imageCoverage:number;status:string}>}
export type QuestionSet={id:string;title:string;description:string;subject:string;grade:string;collectionType?:'topic'|'paper'|'question_type'|'mixed';topicLabel?:string;price:number;status:string;questionCount:number;questionIds?:string[]}
const key='organizer_session_v1'
export const session={get:()=>{try{return JSON.parse(localStorage.getItem(key)||'null') as Session|null}catch{return null}},set:(v:Session|null)=>v?localStorage.setItem(key,JSON.stringify(v)):localStorage.removeItem(key)}
async function request<T>(path:string,init:RequestInit={}){const headers=new Headers(init.headers);const current=session.get();if(current){headers.set('Authorization',`Bearer ${current.token}`);headers.set('X-User-Id',current.user.id);headers.set('X-User-Role',current.user.role)}const response=await fetch(base+path,{...init,headers});if(!response.ok){const error=await response.json().catch(()=>null);throw new Error(error?.message||`请求失败 (${response.status})`)}if(response.status===204)return undefined as T;return response.json() as Promise<T>}
async function authenticatedBlob(path:string){const headers=new Headers();const current=session.get();if(current){headers.set('Authorization',`Bearer ${current.token}`);headers.set('X-User-Id',current.user.id);headers.set('X-User-Role',current.user.role)}const normalized=path.startsWith('/api/')?path.slice(4):path;const response=await fetch(base+normalized,{headers});if(!response.ok)throw new Error(`图片加载失败 (${response.status})`);return response.blob()}
export const api={
 login:(account:string,password:string)=>request<Session>('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({account,password})}),
 register:(displayName:string,mobile:string,password:string)=>request<Session>('/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName,mobile,password,role:'organizer'})}),
 dashboard:()=>request<any>('/organizer/dashboard'),papers:()=>request<Paper[]>('/organizer/papers'),
 upload:(files:File[],data:{title:string;subject:string;grade:string})=>{const body=new FormData();files.forEach(f=>body.append('file',f));Object.entries(data).forEach(([k,v])=>body.append(k,v));return request<Paper|Paper[]>('/organizer/papers',{method:'POST',body})},
 deletePaper:(id:string)=>request<void>(`/organizer/papers/${encodeURIComponent(id)}`,{method:'DELETE'}),
 processing:(id:string)=>request<ProcessingDetail>(`/papers/${encodeURIComponent(id)}/processing`),retry:(id:string)=>request<ProcessingDetail>(`/papers/${encodeURIComponent(id)}/processing/retry`,{method:'POST'}),confirmedQuestions:()=>request<Question[]>('/organizer/questions'),
 knowledgePoints:()=>request<KnowledgePoint[]>('/organizer/knowledge-points'),createKnowledgePoint:(data:{name:string;subject:string;grade:string;parentId?:string})=>request<KnowledgePoint>('/organizer/knowledge-points',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),assignKnowledgePoints:(questionId:string,knowledgePointIds:string[])=>request<{questionId:string;knowledgePointIds:string[]}>(`/organizer/questions/${encodeURIComponent(questionId)}/knowledge-points`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({knowledgePointIds})}),
 questions:(id:string)=>request<Question[]>(`/organizer/papers/${encodeURIComponent(id)}/questions`),
 saveQuestion:(q:Question)=>request<Question>(`/organizer/questions/${encodeURIComponent(q.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(q)}),
 reprocessQuestion:(id:string,sourceRegions:NonNullable<Question['sourceRegions']>)=>request<Question&{reprocessJobId:string}>(`/questions/${encodeURIComponent(id)}/reprocess`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceRegions})}),
 reprocessStatus:(id:string,jobId:string)=>request<{status:string;stage:string;errorMessage?:string}>(`/questions/${encodeURIComponent(id)}/reprocess/${encodeURIComponent(jobId)}`),
 sets:()=>request<QuestionSet[]>('/organizer/question-sets'),createSet:(data:any)=>request<QuestionSet>('/organizer/question-sets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),updateSet:(id:string,data:any)=>request<QuestionSet>(`/organizer/question-sets/${encodeURIComponent(id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),publishSet:(id:string)=>request<QuestionSet>(`/organizer/question-sets/${encodeURIComponent(id)}/publish`,{method:'POST'}),unpublishSet:(id:string)=>request<QuestionSet>(`/organizer/question-sets/${encodeURIComponent(id)}/unpublish`,{method:'POST'}),deleteSet:(id:string)=>request<void>(`/organizer/question-sets/${encodeURIComponent(id)}`,{method:'DELETE'}),
 pageBlob:(paperId:string,pageNumber:number)=>authenticatedBlob(`/papers/${encodeURIComponent(paperId)}/pages/${pageNumber}`),
 pageLocation:(paperId:string,pageNumber:number)=>request<{url:string}>(`/papers/${encodeURIComponent(paperId)}/pages/${pageNumber}/location`),
 assetBlob:(path:string)=>authenticatedBlob(path),
 cropUrl:(path:string)=>base.replace(/\/api$/,'')+path
}
