<script setup lang="ts">
import { computed,onMounted,ref,watch } from 'vue'
import { AlertTriangle,Archive,BookOpenCheck,CheckCircle2,ChevronRight,FileStack,LayoutDashboard,LogOut,Plus,RefreshCw,Search,Settings2,ShoppingBag,UploadCloud,WandSparkles } from 'lucide-vue-next'
import { api,session,type Paper,type PresentationLayout,type ProcessingDetail,type Question,type QuestionSet } from './api'
import SourcePaperPreview from './components/SourcePaperPreview.vue'
import MathPreview from './components/MathPreview.vue'
import AuthenticatedImage from './components/AuthenticatedImage.vue'
import LayoutCanvasEditor from './components/LayoutCanvasEditor.vue'
import QuestionSetAssembler from './components/QuestionSetAssembler.vue'
type Page='dashboard'|'tasks'|'papers'|'review'|'sets'|'assembly'
const current=ref(session.get()),page=ref<Page>('dashboard'),papers=ref<Paper[]>([]),questions=ref<Question[]>([]),confirmedQuestions=ref<Question[]>([]),sets=ref<QuestionSet[]>([]),selectedPaper=ref<Paper|null>(null),selectedQuestion=ref<Question|null>(null),busy=ref(false),error=ref(''),toast=ref('')
const processingDetail=ref<ProcessingDetail|null>(null)
const regionEditing=ref(false)
const recognizing=ref(false)
const layoutOpen=ref(false)
const authMode=ref<'login'|'register'>('login'),auth=ref({name:'',account:'',password:''})
const showAuth=ref(false)
const uploadOpen=ref(false),files=ref<File[]>([]),upload=ref({title:'',subject:'数学',grade:'初三'})
const setOpen=ref(false),setForm=ref({title:'',description:'',subject:'数学',grade:'初三',collectionType:'topic' as 'topic'|'paper'|'question_type'|'mixed',topicLabel:'',price:19.9,questionIds:[] as string[]})
const setTab=ref<'mine'|'sales'>('mine'),editingSetId=ref<string|null>(null)
const stats=computed(()=>({total:papers.value.length,reviewing:papers.value.filter(p=>['processing','review'].includes(p.status)).length,done:papers.value.reduce((n,p)=>n+p.reviewedCount,0),published:sets.value.filter(s=>s.status==='published').length}))
function notify(v:string){toast.value=v;setTimeout(()=>toast.value='',2400)}
function warningLabel(value:string){return ({question_start_not_found:'未定位到题号，当前使用整页区域',last_question_boundary_uses_document_end:'末题区域延伸到试卷内容结尾',cross_page_question_merged:'已自动合并跨页内容',source_region_verified_from_layout_v3:'题目区域已通过版面检测校验'} as Record<string,string>)[value]||value}
async function run(task:()=>Promise<void>){busy.value=true;error.value='';try{await task()}catch(e){error.value=e instanceof Error?e.message:'操作失败'}finally{busy.value=false}}
async function authenticate(){await run(async()=>{const result=authMode.value==='login'?await api.login(auth.value.account,auth.value.password):await api.register(auth.value.name,auth.value.account,auth.value.password);if(result.user.role!=='organizer')throw new Error('该账号不是试题整理人员账号');session.set(result);current.value=result;await load()})}
async function load(){await Promise.all([api.papers().then(v=>papers.value=v),api.sets().then(v=>sets.value=v),api.confirmedQuestions().then(v=>confirmedQuestions.value=v)])}
async function openPaper(p:Paper){selectedPaper.value=p;page.value='review';processingDetail.value=null;regionEditing.value=false;if(p.status==='processing'){questions.value=[];processingDetail.value=await api.processing(p.id);return}await run(async()=>{questions.value=await api.questions(p.id);selectedQuestion.value=questions.value[0]||null})}
async function refreshPaper(){if(!selectedPaper.value)return;await run(async()=>{const status=await api.processing(selectedPaper.value!.id);processingDetail.value=status;notify(`解析进度 ${status.progress}% · ${status.stage}`);await load();const fresh=papers.value.find(p=>p.id===selectedPaper.value!.id);if(fresh){selectedPaper.value=fresh;if(fresh.status!=='processing')await openPaper(fresh)}})}
async function reparsePaper(){
 if(!selectedPaper.value||busy.value)return
 if(!window.confirm('重新解析会重新执行整份试卷的版面检测、OCR 和切题，并更新当前识别结果。确定继续吗？'))return
 await run(async()=>{
  processingDetail.value=await api.retry(selectedPaper.value!.id)
  selectedPaper.value={...selectedPaper.value!,status:'processing',progress:0}
  questions.value=[]
  selectedQuestion.value=null
  regionEditing.value=false
  notify('已提交重新解析，请稍后刷新进度')
  await load()
  const fresh=papers.value.find(item=>item.id===selectedPaper.value!.id)
  if(fresh)selectedPaper.value=fresh
 })
}
async function retryTask(p:Paper){await run(async()=>{await api.retry(p.id);await load();notify('已重新启动试卷解析任务')})}
async function submitUpload(){if(!files.value.length)return error.value='请选择 PDF 或图片';await run(async()=>{const paper=await api.upload(files.value,upload.value);uploadOpen.value=false;files.value=[];await load();notify('上传成功，AI 已开始解析');await openPaper(paper)})}
async function saveQuestion(){if(!selectedQuestion.value)return;await run(async()=>{selectedQuestion.value=await api.saveQuestion({...selectedQuestion.value!,status:'confirmed'});const i=questions.value.findIndex(q=>q.id===selectedQuestion.value!.id);questions.value[i]=selectedQuestion.value!;notify('校对结果已保存');await load()})}
async function saveLayout(layout:PresentationLayout){if(!selectedQuestion.value)return;selectedQuestion.value={...selectedQuestion.value,presentationLayout:layout};await saveQuestion();layoutOpen.value=false}
function updateRegions(regions:NonNullable<Question['sourceRegions']>){if(selectedQuestion.value)selectedQuestion.value={...selectedQuestion.value,sourceRegions:regions}}
async function toggleRegionEditing(){if(!regionEditing.value){regionEditing.value=true;return}if(!selectedQuestion.value)return;await run(async()=>{selectedQuestion.value=await api.saveQuestion(selectedQuestion.value!);const index=questions.value.findIndex(item=>item.id===selectedQuestion.value!.id);if(index>=0)questions.value[index]=selectedQuestion.value!;regionEditing.value=false;notify('切题区域已保存并生成新版本')})}
function setFigurePosition(value:'above'|'below'|'inline'){if(selectedQuestion.value)selectedQuestion.value={...selectedQuestion.value,presentationLayout:{...selectedQuestion.value.presentationLayout,figurePosition:value}}}
async function reprocessSelected(){if(!selectedQuestion.value?.sourceRegions?.length||recognizing.value)return;recognizing.value=true;error.value='';try{const currentId=selectedQuestion.value.id;const queued=await api.reprocessQuestion(currentId,selectedQuestion.value.sourceRegions);for(let attempt=0;attempt<90;attempt++){await new Promise(resolve=>setTimeout(resolve,2000));const state=await api.reprocessStatus(currentId,queued.reprocessJobId);if(state.status==='failed')throw new Error(state.errorMessage||'重新识别失败');if(state.status==='done'){questions.value=await api.questions(selectedPaper.value!.id);selectedQuestion.value=questions.value.find(item=>item.id===currentId)||null;regionEditing.value=false;notify('已按调整后的红框重新识别');return}}throw new Error('重新识别等待超时，请稍后刷新')}catch(e){error.value=e instanceof Error?e.message:'重新识别失败'}finally{recognizing.value=false}}
function openSetEditor(item?:QuestionSet){editingSetId.value=item?.id||null;setForm.value=item?{title:item.title,description:item.description||'',subject:item.subject,grade:item.grade,collectionType:item.collectionType||'topic',topicLabel:item.topicLabel||'',price:item.price,questionIds:[...(item.questionIds||[])]}:{title:'',description:'',subject:'数学',grade:'初三',collectionType:'topic',topicLabel:'',price:19.9,questionIds:[]};setOpen.value=true;page.value='assembly'}
function openTeacherStore(){window.open(import.meta.env.VITE_TEACHER_APP_URL||'http://127.0.0.1:5173/?page=question-sets&tab=store','_blank','noopener,noreferrer')}
async function createSet(){await run(async()=>{editingSetId.value?await api.updateSet(editingSetId.value,setForm.value):await api.createSet(setForm.value);setOpen.value=false;editingSetId.value=null;await load();page.value='sets';notify('试题集已保存')})}
function closeSetEditor(){setOpen.value=false;editingSetId.value=null;page.value='sets'}
async function saveSetForm(value:typeof setForm.value){setForm.value=value;await createSet()}
async function publish(s:QuestionSet){await run(async()=>{await api.publishSet(s.id);await load();notify('试题集已发布到老师端商店')})}
async function unpublish(s:QuestionSet){if(!window.confirm('下线后老师端商店将不再展示该试题集，已有购买记录不受影响。确定下线吗？'))return;await run(async()=>{await api.unpublishSet(s.id);await load();notify('试题集已下线，现在可以编辑')})}
function logout(){session.set(null);current.value=null}
onMounted(()=>{if(current.value)load().catch(e=>error.value=e.message)})
watch(page,(next,previous)=>{if(next!==previous&&next!=='review')window.scrollTo({top:0,left:0,behavior:'instant'})})
</script>

<template>
 <div v-if="!current&&!showAuth" class="public-site"><header class="public-header"><div class="public-brand"><div class="brand-mark">知</div><div><b>试题整理中心</b><small>CONTENT STUDIO</small></div></div><nav><button @click="showAuth=true">产品能力</button><button @click="showAuth=true">内容工作流</button><button @click="showAuth=true">试题集服务</button></nav><div><button class="ghost" @click="authMode='login';showAuth=true">登录</button><button class="primary" @click="authMode='register';showAuth=true">申请入驻</button></div></header><main class="public-main"><section class="public-hero"><div><span>AI NATIVE CONTENT WORKSPACE</span><h1>把时间留给判断，<br/>把拆题交给 AI。</h1><p>上传 PDF 或试卷图片，自动完成版面检测、OCR、切题与结构化整理，<br/>让高质量试题更快进入课堂和内容市场。</p><div><button class="primary" @click="authMode='login';showAuth=true"><Plus/>开始整理试题</button><button class="ghost" @click="authMode='login';showAuth=true">了解工作流程<ChevronRight/></button></div></div><div class="public-visual"><div class="paper-sheet"><span>AI PARSING</span><i></i><i></i><i></i><b>24 道题</b></div><WandSparkles/></div></section><section class="public-capabilities"><div class="assembly-heading"><div><span>ONE-CLICK QUESTION SET</span><h2>从原始试卷到可销售试题集</h2><p>一套完整的试题数字化、校对、组装与发行工作流。</p></div></div><div class="assembly-options"><button @click="showAuth=true"><div class="assembly-symbol">01</div><span>AI PARSING</span><h3>智能拆题</h3><p>兼容原生 PDF、扫描件和多张图片，自动识别题目边界与图文内容。</p></button><button class="assembly-primary" @click="showAuth=true"><div><WandSparkles/></div><span>CONTENT REVIEW</span><h3>人工校对</h3><p>在原卷上调整题目区域，重新识别并编辑题干、公式和图片版式。</p><b>进入工作台 <ChevronRight/></b></button><button @click="showAuth=true"><div class="assembly-symbol">03</div><span>QUESTION SET</span><h3>组装发行</h3><p>跨试卷选择已校对题目，组装专题、整卷或题型精选并上架销售。</p></button></div></section></main></div>
 <div v-else-if="!current" class="auth-shell"><button class="auth-back" @click="showAuth=false">← 返回官网首页</button><div class="auth-copy"><div class="brand-mark">知</div><span>知问内容生产中心</span><h1>让高质量试题，<br/>更快进入课堂。</h1><p>面向专业整理人员的试卷数字化、AI 拆题、人工校对与试题集发行平台。</p><div class="auth-feature"><WandSparkles/> AI 完成重复工作，人工掌控内容质量</div></div><form class="auth-card" @submit.prevent="authenticate"><div class="eyebrow">CONTENT OPERATIONS</div><h2>{{authMode==='login'?'登录整理工作台':'创建整理人员账号'}}</h2><p>使用独立账号进入内容生产系统</p><label v-if="authMode==='register'">姓名<input v-model="auth.name" required placeholder="请输入真实姓名"/></label><label>手机号<input v-model="auth.account" required placeholder="11 位手机号"/></label><label>密码<input v-model="auth.password" required type="password" placeholder="至少 8 位"/></label><div v-if="error" class="error">{{error}}</div><button class="primary wide" :disabled="busy">{{busy?'请稍候…':authMode==='login'?'登录':'注册并进入'}}</button><button type="button" class="link" @click="authMode=authMode==='login'?'register':'login'">{{authMode==='login'?'还没有账号？申请入驻':'已有账号？返回登录'}}</button></form></div>
 <div v-else class="shell" :class="{'review-workspace':page==='review'}">
  <aside class="sidebar"><div class="logo-row"><div class="brand-mark">知</div><div><b>试题整理中心</b><small>CONTENT STUDIO</small></div></div><nav><button :class="{active:page==='dashboard'}" @click="page='dashboard'"><LayoutDashboard/>工作概览</button><button :class="{active:page==='tasks'}" @click="page='tasks'"><RefreshCw/>新建任务<span>{{stats.reviewing}}</span></button><button :class="{active:page==='papers'||page==='review'}" @click="page='papers'"><FileStack/>试卷工作台</button><button :class="{active:page==='sets'}" @click="page='sets'"><BookOpenCheck/>试题集发行</button></nav><div class="quality-card"><div><CheckCircle2/>本周质量</div><strong>98.6%</strong><small>已校对 {{stats.done}} 道题</small></div><button class="account" @click="logout"><div class="avatar">{{current.user.displayName.slice(0,1)}}</div><span><b>{{current.user.displayName}}</b><small>试题整理人员</small></span><LogOut/></button></aside>
  <main class="main"><header><div><div class="eyebrow">TEACHER AGENT · CONTENT SUPPLY</div><h2>{{page==='dashboard'?'工作概览':page==='tasks'?'新建任务':page==='papers'?'试卷工作台':page==='review'?'拆题校对':'试题集发行'}}</h2></div><div class="header-actions"><button class="ghost"><Search/>搜索</button><button class="primary" @click="uploadOpen=true"><UploadCloud/>上传试卷</button></div></header>
   <div v-if="error" class="error global">{{error}}<button @click="error=''">×</button></div>
   <section v-if="page==='dashboard'" class="content"><div class="hero"><div><span>今日内容生产</span><h1>把时间留给判断，<br/>把拆题交给 AI。</h1><p>上传 PDF 或试卷图片，系统自动识别、切题并生成待校对任务。</p><button class="primary" @click="uploadOpen=true"><Plus/>创建整理任务</button></div><div class="hero-visual"><div class="paper-sheet"><span>AI PARSING</span><i></i><i></i><i></i><b>24 道题</b></div><WandSparkles/></div></div><div class="stat-grid"><article><span>累计试卷</span><strong>{{stats.total}}</strong><small>份内容资产</small></article><article><span>处理中</span><strong>{{stats.reviewing}}</strong><small>等待解析或校对</small></article><article><span>已校对试题</span><strong>{{stats.done}}</strong><small>道可用试题</small></article><article><span>已发布试题集</span><strong>{{stats.published}}</strong><small>个在售商品</small></article></div><section class="quick-assembly"><div class="assembly-heading"><div><span>ONE-CLICK QUESTION SET</span><h2>一键组装试题集</h2><p>从已完成校对的试题出发，快速组合专题、整卷或题型精选。</p></div><button class="ghost" @click="page='sets'">管理试题集<ChevronRight/></button></div><div class="assembly-options"><article><div class="assembly-symbol">ƒ</div><span>TOPIC COLLECTION</span><h3>知识专题</h3><p>跨试卷聚合同一知识点，形成可持续更新的专题内容。</p></article><button class="assembly-primary" @click="openSetEditor()"><div><WandSparkles/></div><span>SMART ASSEMBLY</span><h3>一键组装试题集</h3><p>进入组装台，从不同试卷选择已校对题目并设置售价。</p><b>开始组装 <ChevronRight/></b></button><article><div class="assembly-symbol">A</div><span>QUESTION TYPE</span><h3>题型精选</h3><p>按选择题、填空题、解答题等维度组织精品题目。</p></article></div></section></section>
   <section v-else-if="page==='tasks'" class="content task-center"><div class="task-center-head"><div><span>BACKGROUND AI TASKS</span><h1>后台 AI 任务</h1><p>耗时解析任务异步运行，你可以继续使用其他页面。</p></div><div><span class="running-dot"></span>{{stats.reviewing}} 项运行</div></div><div class="html-task-list"><article v-for="p in papers" :key="p.id" class="html-task"><div><span class="task-badge" :data-status="p.status">{{p.status==='processing'?'试卷解析':p.status==='failed'?'解析失败':'内容整理'}}</span></div><div class="task-main"><b>{{p.status==='processing'?'解析试卷：':p.status==='failed'?'解析失败：':'整理完成：'}}{{p.title}}</b><small v-if="p.status==='processing'">正在执行版面检测、OCR 与题目切分 · 约 {{p.progress}}%</small><small v-else-if="p.status==='failed'">{{p.errorMessage||'解析任务执行失败，请重新开始'}}</small><small v-else>识别 {{p.questionCount}} 道题 · 已校对 {{p.reviewedCount}} 道</small><div class="task-progress"><i :style="{width:p.progress+'%'}" :data-status="p.status"></i></div></div><div class="task-end"><small>{{p.status==='processing'?'处理中':p.status==='failed'?'失败':'已完成'}} · {{p.progress}}%</small><button v-if="p.status==='failed'" class="primary" :disabled="busy" @click="retryTask(p)">重新开始</button><button v-else class="ghost" @click="openPaper(p)">{{p.status==='processing'?'查看进度':'打开结果'}}</button></div></article><div v-if="!papers.length" class="task-empty"><RefreshCw/><b>暂无后台任务</b><span>上传试卷后，解析任务会显示在这里。</span><button class="primary" @click="uploadOpen=true"><Plus/>新建任务</button></div></div></section>
   <section v-else-if="page==='papers'" class="content"><div class="filter-bar"><div class="search"><Search/><input placeholder="搜索试卷名称、年级或学科"/></div><button class="filter active">全部 {{papers.length}}</button><button class="filter">待校对 {{stats.reviewing}}</button></div><div class="paper-grid"><article v-for="p in papers" :key="p.id" class="paper-card" @click="openPaper(p)"><div class="cover"><span>{{p.subject}}</span><div class="mini-paper"><i></i><i></i><i></i><i></i></div><b>{{p.grade}}</b></div><div class="card-body"><div class="row"><span class="status" :data-status="p.status">{{p.status==='processing'?'解析中':p.status==='review'?'待校对':'可发行'}}</span><small>{{new Date(p.createdAt).toLocaleDateString()}}</small></div><h3>{{p.title}}</h3><p>{{p.pageCount}} 页 · 识别 {{p.questionCount}} 道 · 已校对 {{p.reviewedCount}} 道</p><div class="meter"><i :style="{width:p.progress+'%'}"></i></div><button>{{p.status==='processing'?'查看解析进度':'进入校对'}}<ChevronRight/></button></div></article><button class="new-paper" @click="uploadOpen=true"><Plus/><b>上传新试卷</b><span>支持 PDF、JPG、PNG、WEBP</span></button></div></section>
   <section v-else-if="page==='review'" class="review-shell"><div class="review-top"><button class="back" @click="page='papers'">← 返回试卷</button><div><b>{{selectedPaper?.title}}</b><small>{{selectedPaper?.grade}} · {{selectedPaper?.subject}}</small></div><div class="review-actions"><button class="ghost" :disabled="busy" @click="refreshPaper"><RefreshCw/>刷新解析结果</button><button class="reparse-button" :disabled="busy||selectedPaper?.status==='processing'" @click="reparsePaper"><WandSparkles/>{{busy?'提交中':'重新解析'}}</button></div></div><div v-if="selectedPaper?.status==='processing'" class="processing"><div class="ai-orb"><WandSparkles/></div><h2>AI 正在识别并拆分试题</h2><p>当前进度 {{selectedPaper.progress}}%，解析完成后即可逐题校对。</p><div class="big-meter"><i :style="{width:selectedPaper.progress+'%'}"></i></div><button class="primary" @click="refreshPaper">刷新进度</button></div><div v-else class="review-grid"><aside class="question-nav"><div class="panel-head"><div><h3>题目列表</h3><p>{{questions.length}} 道题</p></div></div><button v-for="q in questions" :key="q.id" :class="{active:selectedQuestion?.id===q.id}" @click="selectedQuestion={...q}"><span>{{q.number}}</span><div><b>{{q.type}}</b><small>{{q.stem.slice(0,28)}}…</small></div><CheckCircle2 v-if="q.status==='confirmed'"/></button></aside><div class="source-preview"><div class="preview-toolbar"><span>原题截图</span><button class="ghost"><Settings2/>调整切题区域</button></div><div class="crop-placeholder"><Archive/><p>题目原始版面预览</p><small>保留图形、公式与题干相对位置</small></div></div><aside v-if="selectedQuestion" class="inspector"><div class="confidence"><WandSparkles/>AI 置信度 <b>{{selectedQuestion.confidence}}%</b></div><label>题号<input v-model.number="selectedQuestion.number" type="number"/></label><label>题型<select v-model="selectedQuestion.type"><option>选择题</option><option>填空题</option><option>解答题</option></select></label><label>题干<textarea v-model="selectedQuestion.stem" rows="6"/></label><label>答案<textarea v-model="selectedQuestion.answer" rows="3"/></label><label>解析<textarea v-model="selectedQuestion.analysis" rows="5"/></label><label>难度<select v-model="selectedQuestion.difficulty"><option>低</option><option>中</option><option>高</option></select></label><button class="primary wide" @click="saveQuestion"><CheckCircle2/>确认并保存本题</button></aside></div></section>
   <section v-else class="content sets-page">
    <div class="set-management-bar"><div class="set-tabs"><button :class="{active:setTab==='mine'}" @click="setTab='mine'"><BookOpenCheck/>我的试题集 <b>{{sets.length}}</b></button><button :class="{active:setTab==='sales'}" @click="setTab='sales'"><ShoppingBag/>销售与结算</button></div><button class="primary" @click="openSetEditor()"><Plus/>创建试题集</button></div>
    <div v-if="setTab==='mine'" class="set-list-panel"><div class="set-list-header"><span>试题集信息</span><span>内容类型</span><span>题目</span><span>售价</span><span>状态</span><span>操作</span></div><article v-for="s in sets" :key="s.id" class="set-list-row"><div class="set-list-title"><div><BookOpenCheck/></div><span><b>{{s.title}}</b><small>{{s.description||'尚未填写试题集介绍'}}</small></span></div><span class="set-dimension">{{s.topicLabel||s.subject+' · '+s.grade}}<small>{{s.collectionType==='paper'?'完整试卷':s.collectionType==='question_type'?'题型精选':s.collectionType==='mixed'?'混合精选':'知识专题'}}</small></span><b>{{s.questionCount}} 道</b><strong>¥{{s.price}}</strong><span><i class="status" :data-status="s.status">{{s.status==='published'?'销售中':'草稿'}}</i></span><div class="set-row-actions"><template v-if="s.status==='published'"><button class="ghost" @click="openTeacherStore">查看商店</button><button class="offline-button" :disabled="busy" @click="unpublish(s)">下线</button></template><template v-else><button class="ghost" @click="openSetEditor(s)">编辑</button><button class="primary" @click="publish(s)">发布</button></template></div></article><div v-if="!sets.length" class="set-list-empty"><BookOpenCheck/><b>还没有试题集</b><span>从已校对题目中组装第一个可销售内容资产</span><button class="primary" @click="openSetEditor()"><Plus/>创建试题集</button></div></div>
    <div v-else class="sales-panel"><ShoppingBag/><h2>销售与结算</h2><p>已发布 {{sets.filter(item=>item.status==='published').length}} 个试题集</p><div><article><span>累计销售额</span><strong>¥0.00</strong></article><article><span>待结算</span><strong>¥0.00</strong></article><article><span>累计订单</span><strong>0</strong></article></div></div>
   </section>
  </main>
  <div v-if="uploadOpen" class="modal-mask" @click.self="uploadOpen=false"><form class="modal" @submit.prevent="submitUpload"><div class="modal-head"><div><div class="eyebrow">NEW PROCESSING JOB</div><h2>上传试卷</h2></div><button type="button" @click="uploadOpen=false">×</button></div><label class="dropzone"><UploadCloud/><b>选择 PDF 或试卷图片</b><span>单个 PDF，或最多 30 张按顺序排列的图片</span><input type="file" accept="application/pdf,image/*" multiple @change="files=Array.from(($event.target as HTMLInputElement).files||[])"/><em v-if="files.length">已选择 {{files.length}} 个文件</em></label><label>任务名称<input v-model="upload.title" required placeholder="例如：2026 杭州中考数学模拟卷"/></label><div class="form-row"><label>学科<select v-model="upload.subject"><option>数学</option><option>语文</option><option>英语</option><option>物理</option><option>化学</option></select></label><label>年级<select v-model="upload.grade"><option>初一</option><option>初二</option><option>初三</option><option>高一</option><option>高二</option><option>高三</option></select></label></div><button class="primary wide" :disabled="busy">上传并开始 AI 解析</button></form></div>
  <QuestionSetAssembler v-if="page==='assembly'" :questions="confirmedQuestions" :initial="setForm" :editing="!!editingSetId" :saving="busy" @close="closeSetEditor" @save="saveSetForm"/>
  <Teleport v-if="page==='review' && selectedQuestion?.boundaryQuality" to=".inspector">
   <div class="boundary-quality" :data-review="selectedQuestion.boundaryQuality.requiresManualReview"><div><AlertTriangle v-if="selectedQuestion.boundaryQuality.requiresManualReview"/><CheckCircle2 v-else/><b>切题质量 {{selectedQuestion.boundaryQuality.score}}%</b></div><p>{{selectedQuestion.boundaryQuality.crossPage?'该题跨页，已合并多个原卷区域':'该题位于单页原卷区域'}}</p><span v-for="item in selectedQuestion.warnings" :key="item">{{warningLabel(item)}}</span></div>
  </Teleport>
  <Teleport v-if="page==='review' && selectedQuestion" to=".review-actions">
   <button v-if="selectedQuestion.figureUrls?.length" class="layout-button" @click="layoutOpen=true"><Settings2/>调整图文排版</button>
   <button class="primary save-question-top" :disabled="busy" @click="saveQuestion"><CheckCircle2/>{{busy?'保存中':'确认并保存题目'}}</button>
  </Teleport>
  <Teleport v-if="page==='review' && selectedPaper?.status==='processing' && processingDetail" to=".processing">
   <div class="pipeline-detail"><div v-for="item in processingDetail.stages" :key="item.stage+'-'+item.attempt" class="pipeline-stage" :data-status="item.status"><i></i><span><b>{{item.stage}}</b><small>{{item.provider||'系统处理'}} · 第 {{item.attempt}} 次</small></span><em>{{item.status==='completed'?'完成':item.status==='failed'?'失败':'进行中'}}</em></div><div v-if="processingDetail.pages.length" class="page-routing"><b>页面识别策略</b><span v-for="item in processingDetail.pages" :key="item.pageNumber">第 {{item.pageNumber}} 页 · {{item.strategy==='native_with_formula_ocr'?'原生文本 + 公式 OCR':item.strategy==='native'?'原生文本':'整页 OCR'}}</span></div></div>
  </Teleport>
  <Teleport v-if="page==='review' && selectedPaper && selectedQuestion" to=".crop-placeholder">
   <SourcePaperPreview :paper="selectedPaper" :question="selectedQuestion" :recognizing="recognizing" @update:regions="updateRegions" @recognize="reprocessSelected" />
  </Teleport>
  <LayoutCanvasEditor v-if="layoutOpen && selectedQuestion" :question="selectedQuestion" :saving="busy" @close="layoutOpen=false" @save="saveLayout"/>
  <div v-if="toast" class="toast">{{toast}}</div>
 </div>
</template>
