import { createApp } from 'vue';
import App from './App.vue';
import './styles.css';
import './reference-theme.css';
import './review-focus.css';
import './pipeline.css';
import './recognition-quality.css';
import './region-editor.css';
import 'katex/dist/katex.min.css';
import './question-preview.css';
import './task-center.css';
import './public-site.css';
import './brand.css';
import './question-library.css';
import './pagination.css';
createApp(App).mount('#app');
